language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
env:
  - DB=pgsql
  - DB=mysql
matrix:
  allow_failures:
    - php: hhvm
before_install:
  - sudo apt-get update
install:
  - npm install
  # Setup database
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database travis_ci_test;' -U postgres; psql --version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database travis_ci_test;' -uroot; mysql --version; fi

  # Setup Apache, php-fpm and configure Apache Virtual Hosts
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then ./tests/setup-apache-hhvm.sh; else ./tests/setup-apache-php.sh; fi
before_script: rm install/.htaccess
script: npm test && ./tests/validate-php-files.sh && ./tests/install.sh && ./tests/run-migrations.sh && ./tests/phantomjs.sh

after_script:
  - sudo cat /var/log/syslog | grep 'php'
  - sudo cat /var/log/apache2/access.log
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then /tmp/hhvm_access.log; fi
after_failure:
  - sudo cat /var/log/apache2/error.log
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then cat /tmp/hhvm_error.log; else cat /tmp/tmp/php_error.log; fi
  - ./tests/upload-phantom-screenshots.sh
