language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
env:
  - DB=pgsql
  - DB=mysql
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
before_script:
  # Setup database
  - if [[ "$DB" == "pgsql" ]]; then psql -c 'create database travis_ci_test;' -U postgres; psql --version; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database travis_ci_test;' -uroot; mysql --version; fi

  # Setup Apache, php-fpm and configure Apache Virtual Hosts
  - if [[ "$TRAVIS_PHP_VERSION" = "hhvm" ]]; then ./tests/setup-apache-hhvm.sh; else ./tests/setup-apache-php.sh; fi
script: ./tests/install.sh && ./tests/update-feeds.sh && sudo cat /var/log/apache2/error.log
